Check Java 11 in scripts instead from Java

diff --git a/distribution/disttemplates/router/scripts/router b/distribution/disttemplates/router/scripts/router
--- a/distribution/disttemplates/router/scripts/router
+++ b/distribution/disttemplates/router/scripts/router
@@ -1,11 +1,17 @@
 #!/bin/bash
-JAVAHOME=`java -cp ../jars/swiftmq.jar com.swiftmq.JavaHome`
-ISJAVA11=`java -cp ../jars/swiftmq.jar com.swiftmq.IsJava11`
-if [ $ISJAVA11 = "false" ]
-then
-  echo "SwiftMQ requires Java 11 or later installed. Please upgrade your Java installation!"
-  exit -1
+version=$(java -version 2>&1 \
+  | head -1 \
+  | cut -d'"' -f2 \
+  | sed 's/^1\.//' \
+  | cut -d'.' -f1
+)
+
+if [ $version -lt "11" ]; then
+  echo "Java 11 or higher is required."
+  exit 1
 fi
+
+JAVAHOME=`java -cp ../jars/swiftmq.jar com.swiftmq.JavaHome`
 CLASSP="../jars/swiftmq.jar"
 OPENS="--add-opens=java.desktop/java.awt.font=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED  --add-opens=java.base/sun.net.dns=ALL-UNNAMED -Dnashorn.args=--no-deprecation-warning"
 PRECONFIG="-Dswiftmq.preconfig=../data/preconfig/upgrade-to-12.1.0.xml"
